### ISSUE TITLE
Error reading S/MIME message - Exit Code: 2 (Misuse of shell builtins)

### ISSUE THREAD

**Issue by nemesiscb** [filippotoso/p7m-extractor#1]
In some case you can receive this error:

Exit Code: 2(Misuse of shell builtins)

Error Output:
Error reading S/MIME message
23904:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto\asn1\tasn_dec.c:1149:
23904:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:309:Type=PKCS7_ISSUER_AND_SERIAL
23904:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:646:Field=issuer_and_serial, Type=PKCS7_SIGNER_INFO
23904:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:615:Field=signer_info, Type=PKCS7_SIGNED
23904:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:646:
23904:error:0D08403A:asn1 encoding routines:asn1_template_ex_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:496:Field=d.sign, Type=PKCS7

The solution is to use openssl with 'cms' params instead of 'smime'!

I'm not expert of openssl but seems to me that cms is backwards compatible with  'smime'.
I suggest to change it or, even better, let decide this param in the constructor method along with the path or set it with a specific function.

**Comment by filippotoso** [comment]
Check the new getParams() / setParams() methods.

**Comment by nemesiscb** [comment]
even more flexible than my proposed solution in PR, thank you
