### ISSUE TITLE
rsa routines:int_rsa_verify:bad signature - CMS routines:CMS_SignerInfo_verify:verification failure

### ISSUE THREAD

**Issue by nemesiscb** [filippotoso/p7m-extractor#2]
Encountered another error on some p7m file extraction:

Verification failure
140166885725504:error:04091068:rsa routines:int_rsa_verify:bad signature:../crypto/rsa/rsa_sign.c:220:
140166885725504:error:2E09809E:CMS routines:CMS_SignerInfo_verify:verification failure:../crypto/cms/cms_sd.c:767:

After googling a bit I found a solution adding the -no_attr_verify params (and using cms instead o smime).
Hope can help someone.

It would be useful to add the possibility to add params to  P7M->getProcess() and choose between cms/smime.

Relateted to other issue #1

**Comment by filippotoso** [comment]
Check the new getParams() / setParams() methods.

**Comment by nemesiscb** [comment]
even more flexible than my proposed solution in PR, thank you
